import type {
  Application,
  ApplicationPermissionRegistration,
  AuditLog,
  CurrentSession,
  DashboardSummary,
  DirectoryUser,
  FeishuDepartment,
  IamPermissionNode,
  IamRole,
  SyncRun,
} from './types';

export const platformAdminSession: CurrentSession = {
  user: {
    feishuUserId: 'ou_feishu_admin_001',
    displayName: '王文哲',
    departmentPath: '信息化中心 / 平台组',
    status: 'active',
  },
  roles: ['platform_admin'],
  permissions: [
    'dashboard:view',
    'application:view',
    'application:create',
    'application:update',
    'application:disable',
    'application:secret',
    'role:view',
    'role:update',
    'directory:view',
    'sync:view',
    'sync:run',
    'audit:view',
  ],
  applicationIds: ['app_demo_crm'],
};

export const applications: Application[] = [
  {
    id: 'app_demo_crm',
    name: 'Demo CRM',
    code: 'demo-crm',
    description: '销售系统接入演示应用',
    status: 'active',
    appKey: 'app_demo_crm_key',
    appSecretPreview: 'sec_****_crm',
    apiKey: 'api_demo_crm_key',
    apiSecretPreview: 'api_****_crm',
    callbackUrls: ['https://demo.example.com/auth/callback'],
    allowedOrigins: ['https://demo.example.com'],
    ownerFeishuUserId: 'ou_feishu_admin_001',
    ownerName: '王文哲',
    permissionGroupCount: 3,
    permissionPointCount: 12,
    lastApiCalledAt: '2026-05-23T00:20:00.000Z',
    agentPrompt: '将 IAM_APP_SECRET 和 IAM_API_SECRET 作为环境变量写入 demo 系统，禁止提交到 Git。',
    createdAt: '2026-05-23T00:00:00.000Z',
    updatedAt: '2026-05-23T00:00:00.000Z',
  },
  {
    id: 'app_demo_finance',
    name: 'Demo Finance',
    code: 'demo-finance',
    description: '财务系统接入演示应用',
    status: 'active',
    appKey: 'app_demo_finance_key',
    appSecretPreview: 'sec_****_finance',
    apiKey: 'api_demo_finance_key',
    apiSecretPreview: 'api_****_finance',
    callbackUrls: ['https://finance.example.com/auth/callback'],
    allowedOrigins: ['https://finance.example.com'],
    ownerFeishuUserId: 'ou_feishu_admin_001',
    ownerName: '王文哲',
    permissionGroupCount: 1,
    permissionPointCount: 2,
    lastApiCalledAt: '2026-05-22T09:00:00.000Z',
    agentPrompt: '将 IAM_APP_SECRET 和 IAM_API_SECRET 作为环境变量写入 finance 系统，禁止提交到 Git。',
    createdAt: '2026-05-22T08:00:00.000Z',
    updatedAt: '2026-05-22T08:00:00.000Z',
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'audit_sync_success_001',
    action: 'sync.run',
    result: 'success',
    actorFeishuUserId: 'system',
    message: '定时同步成功：更新 18 个用户和 3 个部门',
    requestId: 'req_sync_success_001',
    createdAt: '2026-05-23T00:03:00.000Z',
  },
  {
    id: 'audit_sync_failed_001',
    action: 'sync.run',
    result: 'failed',
    actorFeishuUserId: 'ou_feishu_admin_001',
    message: '手动同步失败：飞书部门列表接口限流',
    requestId: 'req_sync_failed_001',
    createdAt: '2026-05-23T00:35:00.000Z',
  },
  {
    id: 'audit_permission_query_001',
    action: 'permission.query',
    result: 'success',
    actorFeishuUserId: 'ou_sales_001',
    applicationId: 'app_demo_crm',
    message: 'Demo CRM 查询 crm.customer:read 权限',
    requestId: 'req_permission_query_001',
    createdAt: '2026-05-23T00:22:00.000Z',
  },
  {
    id: 'audit_login_001',
    action: 'login',
    result: 'success',
    actorFeishuUserId: 'ou_feishu_admin_001',
    message: '飞书扫码登录管理后台',
    requestId: 'req_login_001',
    createdAt: '2026-05-23T00:18:00.000Z',
  },
  {
    id: 'audit_api_call_001',
    action: 'application.api_call',
    result: 'success',
    actorFeishuUserId: 'system',
    applicationId: 'app_demo_finance',
    message: 'Demo Finance 调用权限查询 API',
    requestId: 'req_api_call_001',
    createdAt: '2026-05-22T09:00:00.000Z',
  },
  {
    id: 'audit_role_update_001',
    action: 'role.update',
    result: 'success',
    actorFeishuUserId: 'ou_feishu_admin_001',
    applicationId: 'app_demo_crm',
    message: '更新 Demo CRM 销售主管授权范围',
    requestId: 'req_role_update_001',
    createdAt: '2026-05-23T00:21:00.000Z',
  },
  {
    id: 'audit_secret_copy_001',
    action: 'secret.copy',
    result: 'success',
    actorFeishuUserId: 'ou_feishu_admin_001',
    applicationId: 'app_demo_crm',
    message: '复制 Demo CRM API secret',
    requestId: 'req_secret_copy_001',
    createdAt: '2026-05-23T00:10:00.000Z',
  },
];

export const syncRuns: SyncRun[] = [
  {
    id: 'sync_run_202605230035',
    trigger: 'manual',
    status: 'failed',
    startedAt: '2026-05-23T00:35:00.000Z',
    finishedAt: '2026-05-23T00:36:20.000Z',
    durationSeconds: 80,
    userChanges: 4,
    departmentChanges: 1,
    operatorFeishuUserId: 'ou_feishu_admin_001',
    requestBatchCount: 8,
    successCount: 6,
    failedCount: 2,
    diffSummary: {
      createdUsers: 1,
      updatedUsers: 2,
      resignedUsers: 1,
      failedUsers: 2,
      createdDepartments: 0,
      updatedDepartments: 1,
    },
    requestId: 'req_sync_failed_001',
    errorMessage: '飞书部门列表接口限流，部分批次未完成。',
    auditLogId: 'audit_sync_failed_001',
  },
  {
    id: 'sync_run_202605230000',
    trigger: 'scheduled',
    status: 'succeeded',
    startedAt: '2026-05-23T00:00:00.000Z',
    finishedAt: '2026-05-23T00:03:00.000Z',
    durationSeconds: 180,
    userChanges: 18,
    departmentChanges: 3,
    operatorFeishuUserId: 'system',
    requestBatchCount: 12,
    successCount: 236,
    failedCount: 0,
    diffSummary: {
      createdUsers: 3,
      updatedUsers: 14,
      resignedUsers: 1,
      failedUsers: 0,
      createdDepartments: 1,
      updatedDepartments: 2,
    },
    requestId: 'req_sync_success_001',
    auditLogId: 'audit_sync_success_001',
  },
  {
    id: 'sync_run_202605230045',
    trigger: 'retry',
    status: 'running',
    startedAt: '2026-05-23T00:45:00.000Z',
    userChanges: 0,
    departmentChanges: 0,
    operatorFeishuUserId: 'ou_feishu_admin_001',
    requestBatchCount: 3,
    successCount: 64,
    failedCount: 0,
    diffSummary: {
      createdUsers: 0,
      updatedUsers: 0,
      resignedUsers: 0,
      failedUsers: 0,
      createdDepartments: 0,
      updatedDepartments: 0,
    },
  },
];

export const applicationPermissionRegistrations: ApplicationPermissionRegistration[] = [
  {
    id: 'perm_demo_crm_customer_read',
    applicationId: 'app_demo_crm_registered',
    groupCode: 'crm.customer',
    groupName: '客户管理',
    permissionCode: 'crm.customer:read',
    permissionName: '查看客户',
    status: 'active',
    updatedAt: '2026-05-23T00:12:00.000Z',
  },
];

export const iamPermissionTree: IamPermissionNode[] = [
  {
    key: 'crm.customer',
    title: '客户管理',
    children: [
      { key: 'crm.customer:read', title: '查看客户' },
      { key: 'crm.customer:update', title: '编辑客户' },
    ],
  },
  {
    key: 'crm.contract',
    title: '合同管理',
    children: [
      { key: 'crm.contract:read', title: '查看合同' },
      { key: 'crm.contract:approve', title: '审批合同' },
    ],
  },
];

export const iamRoles: IamRole[] = [
  {
    id: 'role_demo_crm_sales_admin',
    applicationId: 'app_demo_crm',
    applicationName: 'Demo CRM',
    name: '销售主管',
    code: 'sales-manager',
    description: '负责客户与合同审批的业务主管角色',
    status: 'active',
    permissionGroupCount: 2,
    permissionPointCount: 4,
    departmentBindingCount: 1,
    userBindingCount: 2,
    permissionKeys: ['crm.customer', 'crm.customer:read', 'crm.customer:update', 'crm.contract:read', 'crm.contract:approve'],
    departmentIds: ['dept_sales'],
    userIds: ['ou_feishu_admin_001', 'ou_sales_001'],
    createdAt: '2026-05-23T00:05:00.000Z',
    updatedAt: '2026-05-23T00:22:00.000Z',
  },
  {
    id: 'role_demo_finance_readonly',
    applicationId: 'app_demo_finance',
    applicationName: 'Demo Finance',
    name: '财务只读',
    code: 'finance-readonly',
    description: '仅可查看财务系统基础数据的角色',
    status: 'active',
    permissionGroupCount: 1,
    permissionPointCount: 1,
    departmentBindingCount: 0,
    userBindingCount: 0,
    permissionKeys: ['finance.report:read'],
    departmentIds: [],
    userIds: [],
    createdAt: '2026-05-22T08:10:00.000Z',
    updatedAt: '2026-05-22T08:20:00.000Z',
  },
];

export const feishuDepartments: FeishuDepartment[] = [
  {
    id: 'dept_root',
    name: '飞书 IAM 演示组织',
    path: '飞书 IAM 演示组织',
    userCount: 3,
    updatedAt: '2026-05-23T00:03:00.000Z',
  },
  {
    id: 'dept_it',
    name: '信息化中心',
    parentId: 'dept_root',
    path: '飞书 IAM 演示组织 / 信息化中心',
    userCount: 1,
    updatedAt: '2026-05-23T00:03:00.000Z',
  },
  {
    id: 'dept_sales',
    name: '销售部',
    parentId: 'dept_root',
    path: '飞书 IAM 演示组织 / 销售部',
    userCount: 2,
    updatedAt: '2026-05-23T00:03:00.000Z',
  },
];

export const directoryUsers: DirectoryUser[] = [
  {
    feishuUserId: 'ou_feishu_admin_001',
    displayName: '王文哲',
    departmentId: 'dept_it',
    departmentName: '信息化中心',
    departmentPath: '飞书 IAM 演示组织 / 信息化中心',
    status: 'active',
    email: 'wenzhe@example.com',
    mobile: '13812345678',
    syncedAt: '2026-05-23T00:03:00.000Z',
    localRoleSummary: '平台管理员；Demo CRM / 销售主管',
    lastLoginAt: '2026-05-23T00:18:00.000Z',
    lastPermissionQueriedAt: '2026-05-23T00:20:00.000Z',
  },
  {
    feishuUserId: 'ou_sales_001',
    displayName: '陈销售',
    departmentId: 'dept_sales',
    departmentName: '销售部',
    departmentPath: '飞书 IAM 演示组织 / 销售部',
    status: 'active',
    email: 'sales@example.com',
    mobile: '13987654321',
    syncedAt: '2026-05-23T00:03:00.000Z',
    localRoleSummary: 'Demo CRM / 销售主管',
    lastLoginAt: '2026-05-22T11:30:00.000Z',
    lastPermissionQueriedAt: '2026-05-23T00:16:00.000Z',
  },
  {
    feishuUserId: 'ou_sales_disabled_002',
    displayName: '李停用',
    departmentId: 'dept_sales',
    departmentName: '销售部',
    departmentPath: '飞书 IAM 演示组织 / 销售部',
    status: 'disabled',
    email: 'disabled@example.com',
    mobile: '13700001111',
    syncedAt: '2026-05-23T00:03:00.000Z',
    localRoleSummary: '无本地角色绑定',
  },
];

export const dashboardSummary: DashboardSummary = {
  applicationCount: applications.length,
  permissionPointCount: applications.reduce((total, item) => total + item.permissionPointCount, 0),
  lastSync: {
    status: 'partial_failed',
    startedAt: '2026-05-23T00:00:00.000Z',
    finishedAt: '2026-05-23T00:03:00.000Z',
    departmentTotal: 18,
    userTotal: 236,
    failedCount: 2,
    message: '部分用户状态同步失败，已保留上次有效组织关系。',
  },
  auditEventCount24h: auditLogs.length,
};
